version: '3'
services:
  zookeeper01:
    image: bitnami/zookeeper
    container_name: zookeeper01
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
     ports:
      - "2181:2181"
      - "2000:8080"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_ADMIN_SERVER=yes
      - ZOO_SERVERS=0.0.0.0:2888:3888,192.168.56.103:2888:3888,192.168.56.104:2888:3888 
    networks:
      - kafka-net
  kafka01:
    image: bitnami/kafka
    container_name: kafka01
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper01:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper01
    networks:
      - kafka-net
# === Kafka UI        
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    ports:
      - 9000:8080
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka01:9092
    depends_on:
      - kafka01
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
