version: '3'
services:
  zookeeper01:
    image: bitnami/zookeeper
    container_name: zookeeper01
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "2181:2181"
      - "2000:8080"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_ADMIN_SERVER=yes
      - ZOO_SERVERS=0.0.0.0:2888:3888,192.168.56.103:2888:3888,192.168.56.104:2888:3888
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
